#pragma once

#undef OLED_DISPLAY_128X32
#undef SPLIT_OLED_ENABLE
#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS

//#define SMTD_DEBUG_ENABLED
#define MAX_DEFERRED_EXECUTORS 10 // sm_td
#define TAPPING_TERM 300
