CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes # sm_td
POINTING_DEVICE_DRIVER = pmw3360
SERIAL_DRIVER = vendor